In [2]:
#   Python Programming
#   PGR107-1 22H
#   HomeWork 4
#   11th October 2022

In [3]:
#   API imports and ref
from numpy import array, concatenate, multiply, subtract, power, mod

#   https://numpy.org/doc/stable/user/basics.broadcasting.html
#   https://numpy.org/doc/stable/reference/ufuncs.html

In [4]:
#   P4.1 Write a program to create two arrays of shape (2,2) and (2,1) respectively 
#   containing any number of integers.
#   Concatenate the two arrays and then split it horizontally.

x2d = array( [[3, 4], [5, 6]] )
print( "x2d:\nDimensions: ", x2d.ndim, "\t/Shape: ",x2d.shape,"\nArray:\n",x2d )

y2d = array( [[8], [9]] )
print( "\ny2d:\nDimensions: ", y2d.ndim, "\t/Shape: ",y2d.shape,"\nArray:\n",y2d )

merged = concatenate(( x2d, y2d ), axis=1)
print("\n", merged )

x2d:
Dimensions:  2 	/Shape:  (2, 2) 
Array:
 [[3 4]
 [5 6]]

y2d:
Dimensions:  2 	/Shape:  (2, 1) 
Array:
 [[8]
 [9]]

 [[3 4 8]
 [5 6 9]]


In [5]:
#   P4.2 Give at least three examples along with their codes where broadcasting is not possible.
z = array( [[4,3], [4,5], [7,8]] )
t = array( [[2,1,2], [3,4,4]] )
#   ValueError (3,2) + (2,3) not the same shape, they must be or one of them size 1
#   print( z + t )

a = array( ['1', '2', '3'])
b = array( [2, 3 ])
#   UFuncTypeError not matching types, the two arrays need to be same type
#   print( a+b )

In [9]:
#   P4.3 Create two simple arrays a and b of any number of elements. Apply universal functions (refer to lecture slide#12)
#   on the arguments, array a and array b.

a4 = array( [2, 5, 6, 8, 7] )
b4 = array( [0, 1, 2, 2, 3] )

print("sub 3",  subtract( a4, 3 ))
print("mul", multiply( a4, b4 ))
print("pow", power( a4, b4 ))
print("mod", mod( b4, a4 ))

sub 3 [-1  2  3  5  4]
mul [ 0  5 12 16 21]
pow [  1   5  36  64 343]
mod [0 1 2 2 3]
